Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -45,13 +45,16 @@ jobs:
 
       - name: Deploy to EC2 instances
         run: |
-          # Split the instances into an array
+          set -e
           IFS=$'\n' read -d '' -ra instances <<< "$EC2_INSTANCES"
           for instance in "${instances[@]}"; do
-            ssh ubuntu@"$instance" "docker pull ghcr.io/sarahabuirmeileh/serve-and-shine:${{ steps.image_version.outputs.gitsha }}"
-            ssh ubuntu@"$instance" "docker-compose -f /path/to/your/docker-compose-prod.yml up -d"
+            if ssh ubuntu@"$instance" "docker pull ghcr.io/sarahabuirmeileh/serve-and-shine:${{ steps.image_version.outputs.gitsha }}"; then
+              ssh ubuntu@"$instance" "docker-compose -f /path/to/your/docker-compose-prod.yml up -d"
+            else
+              echo "Failed to SSH into $instance"
+            fi
           done
-      
+        
         env:
           DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
           GIT_VERSION: ${{ steps.image_version.outputs.gitsha }}
